name:                test-synthesizer-sox-nix
version:             0.1.0.0
github:              "thalesmg/test-synthesizer-sox-nix"
license:             GPL-3
author:              "Thales Macedo Garitezi"
copyright:           "2019 Thales Macedo Garitezi"

dependencies:
  - base >= 4.7 && < 5
  - synthesizer-core

executables:
  test-synthesizer-sox-nix:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    extra-libraries:
      - sox
